### ISSUE TITLE
Textdomain array problem in WP LANG

### ISSUE THREAD

**Issue by fxbenard** [fxbenard/test1#13]
The textdomain array function return a string when fetching languages in WP language folder

**Comment by G3ronim0** [comment]
Fix here : https://github.com/fxbenard/test1/commit/2dd85986d2a862cb6ba84a28302aa5524633a2c6

Need tests before merge !

**Comment by fxbenard** [comment]
I'll give it a try this weekend.

**Comment by fxbenard** [comment]
Tested, works like a charm
